name: AWS Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build-container/Dockerfile
          push: true
          tags: altimit/plz-builder:1.0.0
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  ci:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.13.1

    steps:
      - uses: actions/checkout@v1
      - name: Testing Build Commands
        run: |
          ls
          echo "Building ..."
  cd:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.13.1
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Testing Deploy Commands
        run: |
          echo "Deploying ..."